### ISSUE TITLE
Edit Taxonomy: Upload Image does not work

### ISSUE THREAD

**Issue by SpidermanPuddin** [bainternet/Tax-Meta-Class#117]
Images can be uploaded when added in a new taxonomy. However, if you edit that taxonomy images can't upload.

The issue persists even when all plugins are deactivated. The site is secure using SSL.

array('name'=> __('Image ','tax-meta')

**Comment by maxledoux** [comment]
The upload image function also does not work for me. the button does appear on the edit taxonomy page, but clicking on it does nothing.

It did work with my theme (Boss from BuddyBoss) prior to updating to WP 4.4.1.

On the other hand, it continues to work with a different theme on 4.4.1. So that is annoying.

I'm using with a custom post type: `series`.
```
$config = array(
    'id' => 'series_meta_box',          // meta box id, unique per meta box
    'title' => 'Series Info',          // meta box title
    'pages' => array('series'),        // taxonomy name, accept categories, post_tag and custom taxonomies
    'context' => 'normal',            // where the meta box appear: normal (default), advanced, side; optional
    'fields' => array(),            // list of meta fields (can be added by field arrays)
    'local_images' => true,          // Use local or hosted images (meta box images for add/remove)
    'use_with_theme' => true         //change path if used with theme set to true, false for a plugin or anything else for a custom path(default false).
  );


$meta    =  new Tax_Meta_Class($config); 

$meta->addImage('series_image',array('name'=> __('Series Image','tax-meta')));

$meta->Finish();
```

**Comment by bainternet** [comment]
please provide more details, or I wont really be able to  help you.

what theme?
any JS errors? 

does the demo plugin work for you?
if not then what hapens when you try to upload? 

A simple "not Working" is not something I can work with.

**Comment by maxledoux** [comment]
hi, @bainternet, 

Thank you.

In my case, I did have errors in the console for loading the `/css/Tax-meta-class.css` and `/js/tax-meta-clss.js` files due to incorrect paths. However, I fixed that and I'm not getting the errors any more. (I did get `TypeError: $('.at-color').wpColorPicker is not a function. (In '$('.at-color').wpColorPicker()', '$('.at-color').wpColorPicker' is undefined)`, fyi)

Unfortunately, I still was not able to upload images to the taxonomy after fixing those errors.

When I clicked on "Upload Image," simply nothing happened. 

<img width="1271" alt="screen shot 2016-01-30 at 12 08 35 pm" src="https://cloud.githubusercontent.com/assets/12563879/12697160/4a939b60-c74a-11e5-8c9f-0b688b0c187d.png">


I'm using "Boss" theme from buddyboss.com. However, adding images to taxonomies did work with this theme until WP 4.4.1, when I updated my Tax-meta-class files to version 2.1.0 from 1.9.9

I have been testing with no plugins activated.

I have reverted my Tax-meta-class files to 1.9.9 so I am now able to upload images to taxonomies once more.

**Comment by SpidermanPuddin** [comment]
I had the same error with incorrect paths and have resolved that. However, I get the same error as @maxledoux .

`Uncaught TypeError: $(...).wpColorPicker is not a function`

Still unable to upload images. When I click on "Upload Image," nothing happens.

I'm using Genesis and a customized "Magazine" theme. I'm using WordPress 4.4.2 and Tax-meta-class 2.1.0.

I have tested with no plugins active and still the same results.

**Comment by christopher-wilson** [comment]
I'm getting the same `Uncaught TypeError` as @SpidermanPuddin .

**Comment by Eliatrope** [comment]
Hi,

Im getting the same issue on the current version(2.1.0), with the upload image field/upload file field; the paths of css/js are invalid. Someone can share the version 1.9 please ? I need it but i dont know where i can found it... By the way, I use a personal theme(no child-theme used), perhaps this info could be useful

**Comment by brknkfr** [comment]
I have the same problem. Last commit which is working is c815b326520190983f60796f4c4c436c2f165478, after that, file image uploads aren't working anymore.

**Comment by Eliatrope** [comment]
At the moment, im working in local on my project. So, i changed the two options 'local_images'  and 'use_with_theme' from false to true and it works... I dont know if this change is a solution for an online project, but you should maybe try it. Fixed for me right now then, hope this helped you...

**Comment by Akamaozu** [comment]
@maxledoux @SpidermanPuddin @christopher-wilson 

Does [this patch](https://github.com/bainternet/Tax-Meta-Class/pull/122) solve your problem?

**Comment by Eliatrope** [comment]
This seems to be solved for me(but i only tried in local, not with an online website)

**Comment by brknkfr** [comment]
This seems to fix the problem for me locally and on an online website.

**Comment by SpidermanPuddin** [comment]
@Akamaozu That fixes that problem on live. Thanks!

**Comment by Biswash-Developer** [comment]
Warning: Illegal string offset 'url' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1443

Warning: Cannot assign an empty string to a string offset in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1443

Warning: Illegal string offset 'id' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1447

Warning: Cannot assign an empty string to a string offset in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1447

Warning: Illegal string offset 'url' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1449

Warning: Illegal string offset 'url' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1449

Warning: Cannot assign an empty string to a string offset in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1449

Warning: Illegal string offset 'url' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1467


Warning: Illegal string offset 'id' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1469

Warning: Illegal string offset 'url' in D:\xampp\htdocs\projects\edu-medic\wp-content\themes\edu\Tax-meta-class\Tax-meta-class.php on line 1471

**Comment by MaralS** [comment]
I'm developping a plugin and I added custom taxonomies. I try to figure out why the upload image doesn't work.
Here is the code 
`   $config = array(
    'id' => 'ms_author_meta',
    'title' => 'Informations suppl&eacute;mentaires concernant les photographes.',
    'pages' => array('ms_photo_author'),
    'context' => 'normal',
    'fields' => array(),
    'local_images' => true,
    'use_with_theme' => true  );` 
   `$author_meta =  new Tax_Meta_Class($config);` 
   ` $author_meta->addText( 'website',array('name' => 'Site Web'));` 
  ` $author_meta->addImage('avatar',array('name'=> 'Photo de profil'));` 
  ` $author_meta->Finish();`
